[tool.poetry]
name = "snake-2"
version = "0.1.0"
description = ""
authors = ["Louis Di Giorgi <louis.di_giorgi@etu.minesparis.psl.eu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
